### ISSUE TITLE
excluded_dir_patterns not working.

### ISSUE THREAD

**Issue by erwingaitano** [noklesta/SublimeQuickFileCreator#11]
I'm adding this setting in my preferences.sublime-settings file:

```
"excluded_dir_patterns": [
  "tmp",
  "|.git",
  "|.svn",
  "node_modules"
]
```
But the node_modules folder is still being included in the contextual menu.
I've tried `node_modules.*`, `.*node_modules.*`, etc. and not working.

**Comment by twolfson** [comment]
Based on these lines, it looks like you need to set that under a `SublimeQuickFileCreator` key (meaning the README is wrong):

https://github.com/noklesta/SublimeQuickFileCreator/blob/df7b03cc2320fcf75888e34a628982f5284db97f/SublimeQuickFileCreator.py#L38-L44

```js
{
  "SublimeQuickFileCreator": {
    "excluded_dir_patterns": [
      "tmp", "|.git", "|.svn"
    ]
  }
}
```

**Comment by erwingaitano** [comment]
Thank you @twolfson, that was it!

**Comment by twolfson** [comment]
@erwingaitano Do you think you could open a PR to fix it? I'm currently not in a good spot to do it and I'm sure @noklesta would appreciate it =)

**Comment by erwingaitano** [comment]
No problem, I made a PR https://github.com/noklesta/SublimeQuickFileCreator/pull/12
