### ISSUE TITLE
Update description request

### ISSUE THREAD

**Issue by Kristinita** [noklesta/SublimeQuickFileCreator#14]
QuickFileCreator nice work for me in Sublime Text 3. Please, update README.MD and description of your repository. [I can not](http://stackoverflow.com/a/15406659/5951529) change description of your repository in pull request. 

![Description QuickFileCreator](http://i.imgur.com/1TBn1sQ.png)

People may think that only plugin for Sublime Text 2, and will not download QuickFileCreator.

Thanks.

**Comment by noklesta** [comment]
Thanks! Good to hear that it is working for you. I have updated the README and the description.

**Comment by Kristinita** [comment]
@noklesta , but [Caret History](https://github.com/noklesta/Caret-History), unfortunately not supported for Sublime Text 3. Thanks.

**Comment by noklesta** [comment]
That was something I cloned for personal use and just made a tiny change to. Apparently the original repo is no longer on GitHub (and not available on Package Control as far as I can see), and I don't know the code well enough to update it. Anyway, I don't really use ST anymore, so I won't be able to work on it. Sorry - feel free to fork :)
