### ISSUE TITLE
creating list of dirs is slow / exclusion mechanism inflexible

### ISSUE THREAD

**Issue by schnittchen** [noklesta/SublimeQuickFileCreator#5]
Hi,

first of all, I'd LOVE to use this plugin regularly as it really should speed up my workflow. However, I'm working on a project with a lot of directories and it takes up to 20secs to build the list of directories.

I had a look at the way the exclusion mechanism works and it would not be a solution for this problem: I am unable to exclude deep directories from one of the project directories (like 'root/nested/dir'), because the pattern match happens only on the last segment ('dir').

In addition, it would be awesome if the exclusion could optionally leverage the patterns already configured for the user's version control system, i.e. if there's a .gitignore in one of the root directories, optionally use this for directory exclusion below that path.

**Comment by AntoineBoulanger** [comment]
@SeanRoberts Same thing for me.
